### ISSUE TITLE
Side effects in useMemo

### ISSUE THREAD

**Issue by alexandernanberg** [pmndrs/react-three-rapier#10]
First I just want to say great work with this! 

I was reading through the code and noticed that you're calling ` world.createRigidBody` inside `useMemo` which breaks some React rules since `world.createRigidBody` has side effects.  `useMemo` isn't the best choice for this anyway because React can decide to throw away the value at any time and recompute it.

https://github.com/pmndrs/react-three-rapier/blob/a4b9f3fb2ca40abea8f5dcd6d4c44068f60fe398/packages/react-three-rapier/src/hooks.ts#L94-L116

In my own integration I ended up using a getter which as far as I can tell should be React 18+ safe. The approach is described in the bottom of https://github.com/reactwg/react-18/discussions/18

https://github.com/alexandernanberg/playground/blob/973c512aa192a6500a503a15aea6d6dd1b83d2be/src/components/physics.tsx#L265-L272

**Comment by wiledal** [comment]
Thanks for this! Indeed I will have to move everything into effects. It's just not nice working with `current` all the time, and I was hoping to avoid it wherever I could, but I was not aware of these drawbacks.

Your adaption is really nice. Would you like to help flesh out r3f/rapier? 

🇸🇪👋

**Comment by Glavin001** [comment]
@wiledal : To make the DX nicer, what about proxying the rigid body API calls?

**Before:**

- :x: Uses `useMemo`
- ✅  Nice DX without `.current`

```typescript
// Package
export const useRigidBody = <O extends Object3D>(
  // ...
  const rigidBody = useMemo(() => {
    // ...
    const body = world.createRigidBody(rigidBodyDesc);
    return body;
  }, []);
  // ...
  return [ref as MutableRefObject<O>, rigidBody];
};
```

**After:**

- ✅  Uses `useEffect`
- ✅  Nice DX without `.current`

```typescript
export const useRigidBody = <O extends Object3D>(
  // ...
  const rigidBodyRef = useRef();
  useEffect(() => {
    // ...
    const body = world.createRigidBody(rigidBodyDesc);
    rigidBodyRef.current.body;
  }, []);
  // ...
  const api = createBodyApi(rigidBodyRef);
  return [ref as MutableRefObject<O>, api];
};

function createBodyApi(bodyRef) {
  return {
    applyImpulse: (...args) => {
      bodyRef.current.applyImpulse(...args);
    },
    applyTorqueImpulse: (...args) => {
      bodyRef.current.applyImpulse(...args);
    },
    // ...
  };
}
```

Would allow the same public API.

[For example](https://github.com/pmndrs/react-three-rapier/blob/a4b9f3fb2ca40abea8f5dcd6d4c44068f60fe398/demo/src/shapes/Shapes.tsx#L52-L65):

```typescript
// Usage
  const [box, rigidBody] = useCuboid(
    {
      position: [-4 + Math.random() * 8, 10, 0],
    },
    {
      args: [0.5, 0.5, 0.5],
    }
  );

  useEffect(() => {
    rigidBody.applyImpulse({ x: 0, y: 0, z: 0 }, true);
    rigidBody.applyTorqueImpulse({ x: 0, y: 0, z: Math.random() * 0.1 }, true);
  }, []);
  ```

**Comment by wiledal** [comment]
> Would be fun, I'm a bit short on time right now but if I get some spare time later I'll for sure see where I can contribute!

No worries! I might lift some approaches from your repo, as you have it so neatly laid out -- with your permission of course 🙏

> `function createBodyApi(bodyRef) {`

I was thinking of doing this, but the extra work put me off for now. But, I will probably do it anyways because interacting with the api is annoying right now as you have to convert between Rapier's Vector3, Three's Vector3 back and forth for all interactions.

> you can't pass down the rigidbody in context to the child

Hm, supposedly we could initialize the rigidbody in `useLayoutEffect` to get around that...

**Comment by alexandernanberg** [comment]
> with your permission of course

Sure, feel free to take anything that is useful 😄 

> Hm, supposedly we could initialize the rigidbody in useLayoutEffect to get around that...

I _think_ I had to create both the rigidbody and collider in a useLayoutEffect to avoid "layout shift" (not sure what it's called in a 3d context), was some time ago so don't remember exactly why I had to do it that way

**Comment by wiledal** [comment]
> Sure, feel free to take anything that is useful 😄
✨

I've been doing some experiments, and from what I can tell it works okay initializing in a useLayoutEffect and returning a proxy api. 

I have one strange `useLayoutEffect` cleanup function that fires prematurely for some reason, but probably unrelated.

I feel there's big win to only have to deal with Three vector types, so I'll probably continue on this path.

**Comment by wiledal** [comment]
@alexandernanberg you are right, `useLayoutEffect` did not work as we also needed the `world` to be initiated the same.

After more fiddling I believe a combination of these approaches is hitting the goldilocks sweetspot ✨ 

1. Use the `RefGetter` (`MutableRefObject<() => T>`) approach for "lazy" (or rather "eager"!) initiation of objects (`world`, `rigidbody`, `collider`, `joint`), as mentioned in the original post.
2. In a memoized proxy, use the `RefGetter` for all api forwarding

```tsx
const createSomeApi = (refGetter) => ({
  someFunc() => refGetter.current()!.someFunc()
})

const useSomething = () => {
  const ref = useRef()
  const refGetter = useRef(() => {
    if (!ref.current) {
      ref.current = new Something()
    }
    return ref.current
  })

  const api = useMemo(() => createSomeApi(refGetter), [])

  return api
}
```

The result is an immediately accessible api, with eagerly initiated objects.

```tsx
const [ref, api] = useRigidBody(...)

useEffect(() => {
  api.applyImpulse(new Vector3(0,0,1))
}, [])
```

```tsx
  useFrame(() => {
    refs.current.forEach((ref) => {
      const p = ref.current.translation();
      // since p is proxied to be a Vector3, we can easily apply all Threejs math on it
      p.normalize().multiplyScalar(-0.02);
      ref.current.applyImpulse(p);
    });
  });
```

**Comment by wiledal** [comment]
https://github.com/pmndrs/react-three-rapier/pull/14

**Comment by alexandernanberg** [comment]
I'm still not convinced `useMemo` is the right choice here, since React can throw away the value at any time. A lazy state setter might be better (`useState(() => createSomeApi(refGetter))`), but technically it might still violate the React rules since you're setting/getting the ref value in render (React 18 compatibility is hard 😅)
