### ISSUE TITLE
How to use Motors

### ISSUE THREAD

**Issue by brunnolou** [pmndrs/react-three-rapier#11]
From [rapier docs](https://rapier.rs/docs/user_guides/javascript/joints#joint-motors), the motor is accessible from the joint creation.

```ts
let joint = world.createImpulseJoint(params, body1, body2);
(joint as RAPIER.PrismaticJoint).configureMotorVelocity(1.0, 0.5);
```

But the `useImpulseJoint` hook doesn't expose it.

https://github.com/pmndrs/react-three-rapier/blob/4f7440c880295a6f0ea63f2f013e8e06370c3568/packages/react-three-rapier/src/hooks.ts#L410-L432

## Question

How to use Motors? Is there another way?
Are there plans to expose the joint from the hooks?

I'd expect something like this:

```js
const joint = useRevoluteJoint(...)

<Box onClick={() => { joint.configureMotorVelocity(1.0, 0.5); }} />
```

I'd be glad to contribute with a PR.

**Comment by wiledal** [comment]
Yes, the joint API will be available. As the joint needs to initiate in a `useEffect` it will most likely have to return a `RefObject`, which isn't awesome imo.

Feel free to contribute with a PR! I'm in the process of rewriting core initialisation things to be more robust, performant, and allow better control over events etc, but the joints stuff will be left mostly untouched for now, and should be easily adapted.

**Comment by wiledal** [comment]
Update on this: 

Joint APi is coming soon, however it seems that RaperJS is returning `undefined` objects when initiating joints currently. So it's still unusable at this point.

https://github.com/dimforge/rapier.js/issues/83
