### ISSUE TITLE
Will Rapier run in a WebWorker?

### ISSUE THREAD

**Issue by Glavin001** [pmndrs/react-three-rapier#12]
Searching through this code and Rapier docs I was unable to determine if this package would run Rapier in a separate thread/WebWorker, like `use-cannon` does automatically.

**Comment by wiledal** [comment]
It does not. I have no plans of going into that either. 

Running in a web worker sounds good, but then you try a higher volume of meshes:
https://twitter.com/etthugo/status/1514966146029690884

I don't know why it takes use-cannon 30 seconds to start (for 1001 bodies), but I'm assuming it has to do with worker communication and setup. Still very surprising.
