### ISSUE TITLE
Add support for declaratively setting RigidBody userData

### ISSUE THREAD

**Issue by isaac-mason** [pmndrs/react-three-rapier#143]
I ran into a case where I wanted to add user data to a rigid body in order to read it when raycasting. I can do this now with a ref and the raw api, but it would be nice to be able to set rapier user data on `<RigidBody />` declaratively.

I have noted that the RigidBody component and Collider components already have a `userData` prop for body/collider Object3Ds.

---

Here are some approaches I've thought of:

**Option 1: add a rapierUserData prop for the RigidBody userData**

Fairly self-explanatory. One con is if you want some user data on both the Object3D + the rigid body, two props are needed.

**Option 2: use the userData prop as both the three Object3D userData and the rapier RigidBody userData**

Both three.js Object3D userData and rapier RigidBody userData are just arbitrary objects. We could set both of these to the one userData prop. There could be some potential footguns though around expectations of Object3D userData and RigidBody userData always being equal.

---

Option 1 would be my preference for its simplicity, but keen to get thoughts. I'm happy to do the implementation too 🙂

**Comment by wiledal** [comment]
Good point!
I like both of these suggestions 🤔 

In a way I feel the consolidated `userData` passing to both objects is simpler, and perhaps wouldn't hurt...
I kinda want someone with a strong opinion for what makes most sense here 😄

**Comment by isaac-mason** [comment]
I'd be happy with a single `userData` prop that sets both.

It's an easy thing to change in future if use cases pop up for providing different user data to three and rapier objects.

**Comment by isaac-mason** [comment]
If there's no other suggestions on this issue in the coming days, I'll put together a quick PR.

Might also flick it into the discord.

**Comment by hamzakubba** [comment]
I would recommend putting all the rapier-related data in an object like `userData.rapier`. `userData` may be set in blender when exporting a gltf and it's already a standard thing, I think it would be trickier for people to set `rapierUserData` via something like blender out of the box.

**Comment by isaac-mason** [comment]
Please correct me if I'm wrong, but I don't believe user data from models/blender will be affected by this change. The `<RigidBody />` component only sets `userData` for it's own Object3D using the `userData` prop.

If you're using gltfjsx, you'd still need to wrap meshes in `<RigidBody />` components, and that shouldn't interfere with the gltf user data.

**Comment by isaac-mason** [comment]
Closing this now - PR has been merged and released 🎉 (https://github.com/pmndrs/react-three-rapier/pull/154)
