### ISSUE TITLE
`.translation()` does not return the world position systematically

### ISSUE THREAD

**Issue by abernier** [pmndrs/react-three-rapier#173]
I'm facing an odd behaviour to me:

# Description

## ✅ OK Case 1: `position` on `<RigidBody>`

```tsx
<RigidBody ref={bodyRef} colliders="ball"
  position={[3, 3, 3]} // 👈🏻 `position` on RigidBody
>
  <mesh> 
    <icosahedronGeometry />
    <meshStandardMaterial />
  </mesh>
</RigidBody>
```
```tsx
useEffect(() => {
  console.log("translation=", bodyRef.current?.translation());
}, []);
```
outputs: `translation= Vector3 {x: 3, y: 3, z: 3}`

<img width="683" alt="image" src="https://user-images.githubusercontent.com/76580/201954238-374eeaf1-b21a-42b7-a276-1909ba4b7f86.png">

https://codesandbox.io/s/heuristic-ramanujan-emrms9?file=/src/App.tsx:529-549

## ❌ NOK Case 2: `position` on `<mesh>`

```tsx
<RigidBody ref={bodyRef} colliders="ball">
  <mesh
    position={[3, 3, 3]} // 👈🏻 `position` on mesh
  >
    <icosahedronGeometry />
    <meshStandardMaterial />
  </mesh>
</RigidBody>
```
```tsx
useEffect(() => {
  console.log("translation=", bodyRef.current?.translation());
}, []);
```
outputs: `translation= Vector3 {x: 0, y: 0, z: 0}`

<img width="680" alt="image" src="https://user-images.githubusercontent.com/76580/201954300-b9a6dd86-5629-4090-a544-2010a65f1ccc.png">

https://codesandbox.io/s/quirky-microservice-ki7gr7?file=/src/App.tsx:553-573

# Expected

The expected behaviour to me, should be `.translation()` always return `3,3,3` ie. the _real_, _absolute_, _only one_ **world position** of the object

**Comment by abernier** [comment]
As discussed on Discord, and thanks to [@JesproKing's message](https://discord.com/channels/740090768164651008/969941082144124959/1042101959362093106) and @wiledal:

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/76580/201974614-c094f500-a783-41c4-9371-f3f03dbc272e.png">

**Comment by Seanmclem** [comment]
there's got to be more to say about this. How do you get the position of the rigid body? `translation()` doesn't update on every `useFrame`

**Comment by abernier** [comment]
@Seanmclem it seems you're talking about a different problem here. Opening a new issue with your specific details should help, especially with a codesandbox that reproduces it
