### ISSUE TITLE
issue with generating colliders

### ISSUE THREAD

**Issue by sina-developer** [pmndrs/react-three-rapier#174]
Hello
I'm using CuboidCollider for generating a limitless flat plane
problem is visible in image below

![image](https://user-images.githubusercontent.com/26477180/202528465-dce241c3-a3eb-447f-a7ee-f589f7fc3769.png)

first three block on left have collider and other three on right have no any collider 
code for each of them is same and don't now why it's ignoring that part
and when I refresh the page
it keeps ignoring that three!
I'll attach the Code here too
`<RigidBody colliders={false} type="fixed">
        <Center position-y={-2}>
          <mesh
            material={props.material}
            receiveShadow
            scale={[props.scale, 4, props.scale]}
          >
            <boxGeometry />
          </mesh>
        </Center>
        <CuboidCollider
          args={[1, 1, 1]}
          scale={[props.scale / 2, 2, props.scale / 2]}
          position={[0, -2, 0]}
        />
      </RigidBody>`

is there any way to solve this issue?
Thank you

**Comment by wiledal** [comment]
Using the `<Center/>` component can mess with the auto-positioning of the collider within the RidigBody. But as I see that you are creating `CuboidCollider`s yourself, I'm not sure what the issue is here. The snippet you provided there is fine.

Can you give more context on how you are creating these planes?

**Comment by sina-developer** [comment]
Thank you
yeah!
I'll attach the code here
[Floor.txt](https://github.com/pmndrs/react-three-rapier/files/10057803/Floor.txt)


and using this function :

`
let CalcWorldPos = (obj) => {
  obj.updateMatrixWorld();
  let handVec = new THREE.Vector3();
  obj.getWorldPosition(handVec);
  return handVec;
};`

please let me know if you need anything else

**Comment by wiledal** [comment]
Were you able to solve this? It's not clear to me why this wouldn't work. Nothing really stands out in your code there.
I would suggest you use `scale`  less and use the `args` more (so `args={[10,1,10]}` rather than `args={[1,1,1]} scale={[10,1,10]}`. Other than that it's unclear what would cause colliders to not be created just from looking at that code.

**Comment by sina-developer** [comment]
ok
I'll try that
I'll let you know the result 
thanks

**Comment by sina-developer** [comment]
sorry!
forget to reply! 
I tried using args instead of scale
and guess what 😬
nothing changed!

**Comment by trebeljahr** [comment]
I think something similar happens to me... Sometimes the colliders are created, and sometimes they aren't. It's really weird and confusing. 

Basically I am trying out the different collider shapes with code like this: 
```js 
export const TreeWithHullPhysics = () => {
  return (
    <RigidBody position={new Vector3(0, -7.5, 12)} type='fixed' colliders='hull'>
      <Tree1 />
    </RigidBody>
  )
}

export const TreeWithBallPhysics = () => {
  return (
    <RigidBody position={new Vector3(4, -7.5, 12)} type='fixed' colliders='ball'>
      <Tree1 />
    </RigidBody>
  )
}

export const TreeWithCuboidPhysics = () => {
  return (
    <RigidBody position={new Vector3(4, -7.5, 8)} type='fixed' colliders='cuboid'>
      <Tree1 />
    </RigidBody>
  )
}

export const TreeWithPhysics = () => {
  return (
    <RigidBody type='fixed' colliders='trimesh' position={new Vector3(0, -7.5, 8)}>
      <Tree1 />
    </RigidBody>
  )
}
```

```ts
 <Physics colliders='hull'>
    <Debug />
    <FirstPersonController />
    <TreeWithPhysics />
    <TreeWithBallPhysics />
    <TreeWithHullPhysics />
    <TreeWithCuboidPhysics />
</Physics>
```

This leads to them intermittently appearing/disappearing when reloading the page/adding/removing code in the editor... 

not sure if it helps/matters but the relevant files of code are here: 
https://github.com/trebeljahr/react-three-fiber-playground/blob/main/src/pages/first-person-controller.tsx

https://github.com/trebeljahr/react-three-fiber-playground/blob/83b413113bbf61836ae90f88c22698ed8972dcb1/src/components/canvas/TreeStuff.tsx#L54-L94

And no-colliders...
![image](https://user-images.githubusercontent.com/25333032/206878145-8ff32c38-eb3c-458f-9e21-9c24d9f79a3f.png)

But then when cutting some code, saving -> pasting exact same code -> saving again leads to something like this: 
![image](https://user-images.githubusercontent.com/25333032/206878205-39088ea4-af52-471f-9cee-b539287185e3.png)
or this. Basically it "adds" back the missing colliders... 
![image](https://user-images.githubusercontent.com/25333032/206878282-647eac1c-4665-4295-8c62-06b1357a8396.png)

As further context, I am using a next.js-based setup from the r3f next starter... Where the meshes are dynamically imported... maybe that's causing it somehow?

**Comment by trebeljahr** [comment]
just tested that hypothesis, and for what it's worth, at least for me, when not importing the meshes with next/dynamic in between helps to make the bug disappear and the meshes have the colliders generated all the time... 

It would still be cool to figure out why it doesn't work with next/dynamic though in some cases :/

**Comment by wiledal** [comment]
@trebeljahr 
It does sound like the slow initiation of the meshes might be the culprit in that instance.

I would expect this scenario to cause that:

```tsx
<RigidBody>
  <DynamicallyLoadedMesh />
</RigidBody>
```

Since the RigidBody is initiated with no mesh inside, and it won't re-initiate after the mesh has loaded.
A workaround could be to use suspense, and wrap the entire thing.

```tsx
<Suspense>
  <RigidBody>
    <SuspendedDynamicallyLoadedMesh />
  </RigidBody>
</Suspense>
```
