### ISSUE TITLE
Why object inside a rigid bodies shaking when applying linear velocity?

### ISSUE THREAD

**Issue by AmirHo3einJS** [pmndrs/react-three-rapier#181]
![shaking](https://user-images.githubusercontent.com/101206088/203720342-13180a5b-dc2a-45b6-92fe-793a91d19005.gif)
So here is an example, can someone explain to me why this is happening and how can I prevent this?
This is a next js version 13 project and I'm using react three fiber version ^8.9.1 and react three rapier ^0.10.0.
here is the code where I move my rigid body:

![code](https://user-images.githubusercontent.com/101206088/203725607-017ed274-485a-41b8-9d05-cca5ac40bb61.png)
and here is my scene:

![scene](https://user-images.githubusercontent.com/101206088/203726054-092a8165-c8c6-4799-8244-24e5295ba66e.png)

**Comment by wiledal** [comment]
@AmirHo3einJS I have experienced this also when I've tried making simple character controllers.
Does it help turning off interpolation `<Physics interpolate={false} />`, or setting `<Physics typeStep="vary" />`?

**Comment by AmirHo3einJS** [comment]
@wiledal timestep is on vary and setting interpolation to false only make it worse.

**Comment by AmirHo3einJS** [comment]
@wiledal haven't you found some workarounds for this? it's so annoying.

**Comment by schwampf** [comment]
I have the same issue. 
I've been trying to figure out what it could be for hours. Could the cause also lie in the keyboard controls in combination with the rigid bodies?

**Comment by AmirHo3einJS** [comment]
@schwampf I don't think so because I'm not using any keyboard controls. My character follows the mouse. it's a bug. use `<Physics interpolate={false} />` may help you a little bit.

**Comment by gfduck** [comment]
I have the same issue, when move a rigid body with inside a mesh under 60 fps, the mesh shaking. At 60 fps works ok.
We have a solution?
Thanks!

https://user-images.githubusercontent.com/66056030/209580200-b5942f2b-ef37-4989-bd52-47cd88545145.mp4

**Comment by mattblackdev** [comment]
I'm working on an adaptation of the Sketchbook project's third person character controller and I've run into this issue as well.  

I made a sandbox to play around with migrating from use-cannon to rapier and you can really notice this synchronization issue when sprinting or free falling: https://codesandbox.io/s/3rd-person-character-controller-f8h7kg?file=/src/App.tsx

With great velocity comes great jank.

I feel that the future of r3f physics and games lies with react-three/rapier so I'm hopeful that we will figure this out.

**Comment by wiledal** [comment]
I'm investigating this a bit further now, and it seems to be related to the update loop being out of sync with r3f to some regard.

Right now there's a pre-release out `0.14.0-rc.0` that I have tried implementing in one example which does resolve this for me when used with `timeStep="vary"`.

https://codesandbox.io/s/trip-fellas-9d4vm9

**Comment by mattblackdev** [comment]
Thanks @wiledal!! That is fantastic news to me. Version `0.14.0-rc.0` even without `timeStep="vary"` resolves the issue in my sandbox. Interestingly, with debug enabled, you can see that the debug wireframe gets out of sync, but not the model itself. Whereas on `v0.13.2` it was the opposite.

**Comment by wiledal** [comment]
Notes on this:
- in `0.14.0` I have made the `independent` rendering an opt-in feature
  - `<Physics updateLoop="independent" />`
  
I've also done a bunch of tests trying to figure out why the staggering was happening from the start, and it seems to be a combination of things, but it can be relieved by managing the scheduling of the actions, and using `useBeforePhysicsStep` and `useAfterPhysicsStep` in place of `useFrame`.

When you schedule a `useFrame` callback, it likely ends up at the end of the stack (after physics, before rendering the next frame). This may not be what you want.

You can play around with different scheduling by utilizing the updatePriority: `useFrame(() => {...}, -10)`. This can also be set on the `<Physics updatePriority={-10} />` if you are not using the `independent` updateLoop strategy.

All in all, I found that using `useAfterPhysicsStep` for positioning my camera, and `timeStep="vary"` resolves all my staggering issues. Most of it is inconceivable by just adding some good `lerp` for both the cameras `lookAt` and the position.

Work in progress here: https://codesandbox.io/s/trip-fellas-9d4vm9?file=/src/App.tsx
