### ISSUE TITLE
Setup Vercel automatic deployments for Pull Requests

### ISSUE THREAD

**Issue by Glavin001** [pmndrs/react-three-rapier#20]
Would be helpful so we can preview & test Pull Requests, such as #19 .

**Comment by wiledal** [comment]
The `demos` are really only a test-bed for debugging currently, not exactly intended for public consumption.
Since the `/demo` is relying on preconstruct I'm not sure how that would work in a vercel-setting 🤔 

What I really want is some CodeSandbox examples for these things.

**Comment by isaac-mason** [comment]
Vercel should work fine with anything - you can supply any bash command to build and a directory to upload.

I'm happy to lend a hand setting it up if you're keen 🙂

**Comment by wiledal** [comment]
@isaac-mason For sure! Help always appreciated. I'm spending most of my time working on the API when I get chances.

**Comment by isaac-mason** [comment]
@drcmda should be fixed now!

I had to change the base directory from `demo` to the repo root & update the output folder.

Then changed the build command to this: 

```
yarn build && cd demo && npx vite build
```

Ideally we'd also run `tsc` to type check the demo build but thereare some type errors right now.

**Comment by drcmda** [comment]
tsc also crashes locally for me so at least that’s not nexts fault. Thanks!

**Comment by wiledal** [comment]
Thanks for helping with this! 
I'll clear up the tsc issues for the demos.

From what I can tell the https://react-three-rapier-git-feat-deprecate-hook-api-pmndrs.vercel.app/, which should be based on the branch, is actually using what looks to be the latest published version of r3/rapier -- so the Kinematics-demo does not work accurately (the torus should be spinning). 

Defeats the purpose of the preview deployments. Anything that can be done there?

**Comment by isaac-mason** [comment]
With my change, deployments from now should be using the version from the branch - I'll see if I can re-run that preview deployment to make sure!

**Comment by isaac-mason** [comment]
Redeployed this now: https://react-three-rapier-git-feat-deprecate-hook-api-pmndrs.vercel.app/ 

@wiledal let me know if that looks right 🙂

**Comment by wiledal** [comment]
Yes! Looks good!
