### ISSUE TITLE
When Mesh in the RigidBody moves left or right by setLinvel, Mesh moves out of sync with the RigidBody, causing Mesh to shake back and forth

### ISSUE THREAD

**Issue by wlinglinux** [pmndrs/react-three-rapier#202]
![image](https://user-images.githubusercontent.com/286261/207777630-2682fad0-e88f-44d2-bfe0-33955284a092.png)
wrong position left
![image](https://user-images.githubusercontent.com/286261/207777707-800e8914-2522-4cb4-ba00-77dc760da785.png)
wrong position right
![image](https://user-images.githubusercontent.com/286261/207777771-76e11dea-f26b-4b7b-925d-1a346abda28f.png)
right position

**Comment by wiledal** [comment]
The mesh position is interpolated to allow smoother simulations on all framerates.
What happens if you do `interpolate={false}` or `timeStep={'vary'}`?

**Comment by wiledal** [comment]
Duplicates #181

**Comment by wlinglinux** [comment]
thanks
