### ISSUE TITLE
How to synchronize the positions of physical objects with the store?

### ISSUE THREAD

**Issue by fax1ty** [pmndrs/react-three-rapier#241]
I use [zustand](https://github.com/pmndrs/zustand) as a store provider.
I process every position change through callbacks
* [TransformControls](https://github.com/pmndrs/drei#transformcontrols) -> onObjectChange
```ts
            const threeObject = scene.getObjectByName(selectedObject.id);
            if (threeObject)
              moveObject(
                selectedObject,
                new V3(
                  threeObject.position.x,
                  threeObject.position.y,
                  threeObject.position.z
                )
              );
```
* TransformPanel - onChange
![image](https://user-images.githubusercontent.com/26363214/211125554-a30db10a-41bb-44f5-89a7-17ae3d950c83.png)

```ts
       moveObject(
              selectedObject,
              new V3(v, selectedObject.position.y, selectedObject.position.z)
            );
```

How can I handle position changes of physical bodies?

P.S.
```ts
  moveObject: (gameObject, position) => changeObject(gameObject, { position })
  ```
  
  ```ts
  const changeObject = (gameObject: GameObject, props: Partial<GameObject>) => {
  useSceneStore.setState((old) => {
    const copy = [...old.objects];
    const index = copy.findIndex(({ id }) => id === gameObject.id);
    copy[index] = { ...gameObject, ...props };
    return { objects: copy };
  });
  if (useSceneStore.getState().selectedObject?.id === gameObject.id)
    useSceneStore.getState().selectObject({ ...gameObject, ...props });
};
```

**Comment by wiledal** [comment]
In order to change the position of the physical object, you have to access it's reference in the Physics scene.

The best way to do that is getting the `ref` to the `RigidBody`.

```ts
const SomeThing = () => {
  const rigidBodyApi = useRef()

  useEffect(() => {
      rigidBodyApi.current.setTranslation({x, y, z})
   }, [])
  
  return <RigidBody ref={rigidBodyApi}>
    <mesh />
  </RigidBody>
}
```

The object represented in ThreeJS's scene graph will be wrapped by another `Object3D`, which represents the object, so if you are using some `id` of a `<mesh />`, you'll need to adapt your code to target the object represented by the Physics world.

**Comment by wiledal** [comment]
This uses the `RigidBodyApi` to control the position.

https://github.com/pmndrs/react-three-rapier/blob/main/demo/src/examples/api-usage/ApiUsageExample.tsx
As seen here: react-three-rapier.pmnd.rs/api-usage

**Comment by fax1ty** [comment]
But how do I know when to change the position in the store? When did the physical changes occur

**Comment by wiledal** [comment]
You could update this on each frame. You'd have to do the diff-comparison yourself however, as in checking if the store needs to update or not.

Something like:

```tsx
import {useFrame} from '@react-three/rapier'

const _v3 = new Vector3()

const SomeComponent = () => {
  const mesh = useRef<Mesh>()

  useFrame(() => {
    mesh.current.getWorldPosition(_v3)
    // ...
  })

  return <RigidBody>
    <someMesh ref={mesh} />
  </RigidBody>
}
```

You can also add checks for if a body is `awake` and only update the store then.
