### ISSUE TITLE
Set mass

### ISSUE THREAD

**Issue by prasanna-gmail** [pmndrs/react-three-rapier#279]

**Comment by prasanna-gmail** [comment]
How to set mass of a rigid body
as I can see only read mass

**Comment by wiledal** [comment]
Mass is automatically calculated by `Rapier` based on the size of your colliders. 
You can manually `mass` using the `mass` or `massPeoperties` prop on a `<Collider />` or a `<RigidBody />`. This gets complicated however.

https://pmndrs.github.io/react-three-rapier/interfaces/RigidBodyProps.html#mass

I recommend setting the `density` instead, and letting the mass be calculated by `Rapier`.
