### ISSUE TITLE
Creating Character Controller

### ISSUE THREAD

**Issue by flaaudwls** [pmndrs/react-three-rapier#300]
I was trying to build the character controller using kinematicPosition type.
The ground and other buildings are fixed type of rigid body.
The problem is that the ball collider (character kinematic collider) go through the buildings.
Only if the buildings are dynamic type rigibody, the collision detection works.
Is there any way to detect collisions between kinematicPosition type and fixed type?
We shouldn't use the kinematicPosition type for the character collider?

**Comment by wiledal** [comment]
Hey @flaaudwls 👋. It's not recommended to use `kinematicPosition` on player controllers indeed as they are not affected by forces. Better to use a dynamic RigidBody, and move it using velocity based translation.

Here's a basic, semi-hacky test I made a while back: https://codesandbox.io/s/island-c19g5h

Rapier recently added a `kinematicCharacterController`, which can be accessed and used via the `useRapier()` hook. It helps to position objects accurately by applying "character"-rules when translating.

https://rapier.rs/docs/user_guides/javascript/character_controller/

I'm planning to add it as a hook eventually.

**Comment by isaac-mason** [comment]
This isn't polished, but can serve as a starting point for using KinematicCharacterController:

https://sketches.isaacmason.com/#/sketch/Rapier-KinematicCharacterController

https://github.com/isaac-mason/sketches/tree/main/src/sketches/sketch-Rapier-KinematicCharacterController

**Comment by flaaudwls** [comment]
Thank you for sharing this. It is super helpful.

**Comment by ilyich-erd** [comment]
Cool examples! Thanks for sharing.

Today I noticed a cool section on [rapier](https://rapier.rs/docs/user_guides/bevy_plugin/character_controller/#stairs-and-small-obstacles). Is there a way to have `autostep` also with react-three-rapier?

**Comment by wiledal** [comment]
> Today I noticed a cool section on [rapier](https://rapier.rs/docs/user_guides/bevy_plugin/character_controller/#stairs-and-small-obstacles). Is there a way to have `autostep` also with react-three-rapier?

Yes, that is the character controller that I mentioned, and that Isaac has implemented, although you are linking to the `bevy plugin`, not the JavaScript version: https://rapier.rs/docs/user_guides/javascript/character_controller/

It's not super straight forward to work with, as you need to implement your own gravity etc, but it does give you some advantages to using a dynamic RigidBody.
