### ISSUE TITLE
Best way to Lock Rotations?

### ISSUE THREAD

**Issue by nwpointer** [pmndrs/react-three-rapier#31]
Heya, 

Awesome job on this lib so far, really exciting stuff

Was playing around and wanted to lock an objects rotation, found this seemed to work: 
`<RigidBody ref={api=>api.raw().lockRotations(true)}>`

Is that the best way to do this currently? Was thinking something like this would be more ergonomic but unsure of feasibility / implications:

`<RigidBody lockRotations={true}>`

**Comment by wiledal** [comment]
Hello! Thanks for the interest in r3f-rapier.

Yes, rotational and transitional constraints are one the roadmap in fact. The example api you provided here makes sense to me.

I'll include this in the coming version.
More API changes and improvements are coming 🙌
