### ISSUE TITLE
a way to prevent children inside rigidbodies to be treated as colliders

### ISSUE THREAD

**Issue by drcmda** [pmndrs/react-three-rapier#32]
currently everything inside a `<RigidBody>` is being interpreted as a collider, `useRigidBody` will call:

```jsx
const autoColliders = colliderSetting !== false ? createCollidersFromChildren(ref.current, rigidBody, {...options, colliders: colliderSetting}, world) : []
```

which then calls

```jsx
  object.traverse((child: Object3D | Mesh) => {
    if ("isMesh" in child) {
      ...
```

the problem is that this makes it hard to add ornamentals to objects, things that are supposed to be grouped with the main physics object so that they may move along, but that should not create a physics shape.

the only workaround i have found is this:

```jsx
<RigidBody ...>
  <mesh>
    <sphereGeometry />
  </mesh>     
  <mesh traverse={() => null}>
    ...
```

the second mesh would move with the main object, but tricks rapier so that it skips auto shape. imo this is a super common case and something should probably be introduced to make this more comfortable:

```jsx
<RigidBody ...>
  <mesh />
  <mesh skip /> // ?
  <mesh userData={{ rapier: { skip: true } }} /> // ?
```

**Comment by drcmda** [comment]
for reference, hugo made a better suggestion on discord

```jsx
<RigidBody colliders="cuboid">
  <mesh />
</RigidBody>

<RigidBody colliders={false}>
  <Collider type="cuboid">
    <mesh />
  </Collider>
  <mesh />
</RigidBody>
```

**Comment by wiledal** [comment]
I think `<MeshCollider />` is a good name for this. What do you think?

```tsx
<RigidBody colliders={false}>
  {/* Specific colliders */}
  <CuboidCollider args={...} />
  <BallCollider args={...} />

  {/* Mesh-based automatic colliders */}
  <MeshCollider type="trimesh">
    <mesh />
  </MeshCollider>

  <MeshCollider type="hull">
    <mesh />
  </MeshCollider>  

  {/* Decorative meshes, no colliders */}
  <mesh />
</RigidBody>
```
