### ISSUE TITLE
Trying to use joints results in "Uncaught TypeError: useRapier() is undefined"

### ISSUE THREAD

**Issue by ejmelias** [pmndrs/react-three-rapier#320]
I just started using rapier and have been unable to use any of the use____Joint() methods because I get the following error:

Uncaught TypeError: useRapier() is undefined
    useRevoluteJoint react-three-rapier.esm.js:1742

I am trying to use the example straight from the documentation:
`const bodyA = useRef(null); `
`const bodyB = useRef(null);`
`const joint = useRevoluteJoint(bodyA, bodyB, [`
`      [0,0,0],`
`      [0,0,0],`
`      [1,0,0]`
 ` ]);`

Does anyone have any idea how to fix this?

**Comment by wiledal** [comment]
Are you using this within a component that exists within `<Physics>`?
What is your setup for this?

**Comment by ejmelias** [comment]
Here's the setup:
[https://codesandbox.io/s/boring-platform-hx2fj5?file=/src/App.js](url)

**Comment by wiledal** [comment]
This is actually a pitfall related to React contexts, not specifically this library.

You need to initiate the joint on a component inside the `physics` context. It's the same as trying to use `useThree`, or `useFrame` on the component that returns the canvas.

example:
```ts
const App = () => {
  useFrame(() => {
    // Will not work, because this component is not INSIDE <Canvas />
  })
  
  const rapier = useRapier() // Will not work because this component is not INSIDE <Physics />
 
  return (
      <Canvas>
        <Physics />
          <Box />
        </Physics>
      </Canvas>
  )
}
```

```ts
const App = () => {
   useFrame(() => {
      //  Will work, because this component is INSIDE <Canvas />
    })
  
  const rapier = useRapier() // Will work because this component is INSIDE <Physics />

  return <>
    <Box />
  </>
}

const Main = () => { 
  return (
      <Suspense>
        <Canvas>
          <Physics />
            <App />
          </Physics>
        </Canvas>
      </Suspense>
  )
}
```
