### ISSUE TITLE
How to update center of origin position?

### ISSUE THREAD

**Issue by ronjunevaldoz** [pmndrs/react-three-rapier#331]
I'm trying to rotate an base on the top of an object (assume that center of origin is changed in blender gltf), but even I update the origin in blender, it always rotate based on the center.

**Comment by wiledal** [comment]
Rotating things can be a bit confusing. I've seen this question before.

You have your `RigidBody`, and your `Colliders`. When you place a `model` inside of a `RigidBody`, you need to place that model at `[0,0,0]` to ensure that the center of the `RigidBody` corresponds to your model.

For instance:
```ts
const SomeComponent = () => {
  const gltf = useGLTF('/model.glb')

  return (
    <RigidBody 
      position={[gltf.nodes.something.position]}
      rotation={[gltf.nodes.something.rotation]}
    >
      <mesh 
        geometry={gltf.nodes.something.geometry} 
        material={gltf.nodes.something.material}
       />
   </RigidBody>
  )
}
```

☝️ doing that ensures that the model inside the `<RigidBody/>` is positioned where the model was in your blender file, but the model is centered within it.

Does that help?
