### ISSUE TITLE
RigidBody Colliders are not updated.

### ISSUE THREAD

**Issue by flaaudwls** [pmndrs/react-three-rapier#336]
HI, I have a lot of buildings and can't render all of them due to the performance. So I render only some buildings close to the avatar.
These buildings are rigidbodies. 
When I update the buildings based on avatar's position, I think the colliders of the previous buildings stay in the same places.
Basically we need to remove the old colliders and to add new ones of the new buildings.
const [buildings, setBuildings] = useState([])

buildings.map((buildingGeometry, idx)=>
(<RigidBody key={idx} type="fixed" colliders={"trimesh"}>
   <mesh  geometry={buildingGeometry} material={buildingMaterial} /mesh>
</RigidBody>)
)

When I remove some buildings, I still see the old colliders.
Is there any way to remove the colliders when we remove the geometries?

**Comment by wiledal** [comment]
This should totally work 🤔 when you unmount a `<RigidBody />` that body is removed from the simulation. The only problem I can see is if you are actually not removing the bodies, but the `meshes` inside the bodies.

**Comment by wiledal** [comment]
For instance this have unexpected results:

```ts
<RigidBody colliders="trimesh">
  {buildings.map(building =>
    <mesh />
  )}
</RigidBody>
```

This should work better
```ts
{buildings.map(building =>
  <RigidBody colliders="trimesh">
    <mesh />
  </RigidBody
)}
```

I'm doing basically this here:
https://codesandbox.io/s/pensive-julien-f1fdo4?file=/src/App.tsx

**Comment by flaaudwls** [comment]
Thank you for the possible solutions. I will try.

**Comment by flaaudwls** [comment]
Here is the codes I was trying.
   <group ref={groupRef}>
      {groups.map(({ buildingGeo, buildingMatIdx }, idx) => (
        <Fragment key={idx}>
          {buildingGeo && (
            <RigidBody key={idx} type="fixed" colliders={"trimesh"}>
              <mesh
                geometry={createGeometry(buildingGeo)}
                material={buildingMats[`mat${buildingMatIdx}`]}
              />
            </RigidBody>
          )}
        </Fragment>
      ))}
    </group>

Here, setGroups(newGroups) does not remove all the old colliders and even new buildings don't have the colliders.

But the following code is working
setGroups([])
setTimeout( ()=>{
     setGroups(newBuildingGroups)
} , 0)
This totally removes the old geometry.
