### ISSUE TITLE
Gravity change with state

### ISSUE THREAD

**Issue by ClayCooperLA** [pmndrs/react-three-rapier#34]
Hello, here's the first of a few issue I found when converting an experiment from cannon to rapier, as asked!

Doesn’t look like I can change the gravity mid render with state. I have a boolean called `switchModeOn` that alternates on a timer, worked great in cannon to reverse the gravity on the fly!

`/src/BoxFan/index.js` line 81, switchModeOn should be flipping the gravity.
https://codesandbox.io/s/rapier-physics-box-fan-experiment-debug-gravity-kh45y3?file=/src/BoxFan/index.js

**Comment by wiledal** [comment]
Great stuff, implementing this in the next release!
