### ISSUE TITLE
Ghost RigidBody after using setNextKinematicRotation

### ISSUE THREAD

**Issue by steelx** [pmndrs/react-three-rapier#359]
I'm using this below hook to rotate RigidBody’s the mesh is colliding perfect, but its leaving a ghost collider after first frame. You can also view the entire repo here https://github.com/steelx/beat-blocks-js/blob/main/src/hooks/useKinematicRotation.ts
<img width="726" alt="image" src="https://user-images.githubusercontent.com/3184210/228533145-ad3c58b8-b953-49b9-a79c-284879ee07c0.png">

```ts
export const useSimpleRotation = (
	ref: RefObject<RapierRigidBody>,
	speed = 1,
) => {
	useFrame((state) => {
		const time = state.clock.getElapsedTime();
		const eulerRotation = new Euler(0, time * speed, 0);
		const quaternion = new Quaternion();
		quaternion.setFromEuler(eulerRotation);
		ref.current?.setNextKinematicRotation(quaternion);
	});
};
```

```tsx

const Block: React.FC<BlockProps> = ({
	position,
	geometry = boxGeometry,
	material,
	children = null,
}) => {
	return (
		<RigidBody type="fixed" restitution={1}>
			<group position={position}>
				<mesh
					geometry={geometry}
					position={[0, -0.1, 0]}
					scale={[BLOCK_SIZE, 0.2, BLOCK_SIZE]}
					material={material}
					receiveShadow
				/>
				{children}
			</group>
		</RigidBody>
	);
};

const BlockSpinner: React.FC<{ position: Position }> = ({ position }) => {
	const obstacleRef = useRef<RapierRigidBody>(null!);
	useSimpleRotation(obstacleRef, 2);
	return (
		<Block position={position} material={floor2Material}>
			<RigidBody ref={obstacleRef} type="kinematicPosition">
				<mesh
					geometry={boxGeometry}
					material={obstacle1Material}
					scale={[3.5, 0.3, 0.3]}
					castShadow
				/>
			</RigidBody>
		</Block>
	);
};
```

https://user-images.githubusercontent.com/3184210/228531745-5f1017c6-3cf9-490f-bda9-7e517d0c0468.mov

**Comment by wekex35** [comment]
Hi, here you can check simple code-sandbox example: https://codesandbox.io/s/blissful-diffie-zte6cy?file=/src/CylinderCollar.jsx:455-479

**Comment by wiledal** [comment]
Hey @steelx, looking briefly at that code example, I can see that you are nesting `<RigidBody/>` within other `<RigidBody />`, this will cause double mounting of objects and is likely the cause of your problem.

Example:
```tsx
<Block>
  <RigidBody ... />
</Block>
```
Your Block-component already contains a `RigidBody`.

Only allow one `RigidBody` to wrap your colliders and I expect this will start working.
