### ISSUE TITLE
<CuboidCollider /> component doesn't get rerender!

### ISSUE THREAD

**Issue by TheMetaverseEngineer** [pmndrs/react-three-rapier#386]
Hi, I'm using `<CuboidCollider args={state} />`. When I setState, nothing happens, and my collider dimensions doesn't change. Is this a bug?

**Comment by wiledal** [comment]
This could be a bug! Changing the arguments should technically create an entirely new object 🤔

**Comment by TheMetaverseEngineer** [comment]
I think I've found a workaround for this. You can set a key on Component and it will do the job. Like this: `<CuboidCollider key={state} args={state} />`. Just remember, the key prop must be something reactive like a state.
