### ISSUE TITLE
Can i get the complete control of "when Rapier does run"?

### ISSUE THREAD

**Issue by RakaDoank** [pmndrs/react-three-rapier#392]
I came from [cannon-es](https://github.com/pmndrs/cannon-es) library (not the react-three/cannon).
On that library, i can make my own loop and call the `world.fixedStep`, mutate the mesh position, rotation, etc, and then call the `invalidate` to request a new frame

Is it possible right now to approach this like method in react-three/rapier?
I want to get full control of this, like play and stop button.

On demand rendering is only let rapier getting its own loop.

**Comment by wiledal** [comment]
Hello! Yes, you can initiate the `<Physics paused />`  with the `paused` prop, then call the step function manually.
https://github.com/pmndrs/react-three-rapier#manual-stepping

```tsx
const Component = () => {
  const {step} = useRapier()

  useEffect(() => {
    step(1/60)
  }, [])
  
  return ...
}
```

For just a play / stop scenario, it almost seems like you jsut want to control the `paused` prop. Something like:

```tsx
const PlaybackControls = ({isPlaying, onPlaybackChange}) => {
  return (
    <button onClick={() => onPlaybackChange(!isPlaying)}>
      {isPlaying ? 'pause' : 'play'}
    </button>
  )
}

const App = () => {
  const [isPlaying, setIsPlaying] = useState(false)

  return (
  <>
  <Canvas>
    <Physics paused={!isPlaying}>
      ...
    </Physics>
  </Canvas>
  <PlaybackControls isPlaying={isPlaying} setIsPlaying={onPlaybackChange} />
  </>
  )
}
```
