### ISSUE TITLE
TypeError: Cannot destructure property 'rapier' of 'useRapier(...)' as it is undefined.

### ISSUE THREAD

**Issue by jonrrivera** [pmndrs/react-three-rapier#41]
Thanks for the great initiative. I just installed the package and I am trying to get it working on a GLTF like so:

        import { RigidBody } from "@react-three/rapier";
        
        <RigidBody colliders={"hull"} restitution={2}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.perimeter_extrude.geometry}
            material={materials["Material.088"]}
            position={[1180.06, 0, 479.2]}
          />
        </RigidBody>

But getting: 

<img width="1128" alt="Screen Shot 2022-07-20 at 2 18 22 PM" src="https://user-images.githubusercontent.com/18686388/180083962-a41a001f-893a-4385-8513-e2fd7a4fb166.png">

can someone point me in the right direction please? 

thanks!

**Comment by wiledal** [comment]
Hey!

Did you wrap your objects in Suspense and Physics?

```tsx
<Canvas>
  <Suspense>
    <Physics>
      <RigidBody ... />
    </Physics>
  </Suspense>
</Canvas>
```

**Comment by wiledal** [comment]
I understand your confusion. The docs and readme are lacking right now, as most work is going into finalising the APIs.

Here's a small example using a mesh:
https://codesandbox.io/s/react-three-rapier-simple-example-lbkw9b?file=/src/App.tsx
