### ISSUE TITLE
Collider Scale and Position to RigidBody having no effect

### ISSUE THREAD

**Issue by OldManMeta** [pmndrs/react-three-rapier#412]
I am unsure if this is a bug, or just not a feature yet.

In this scenario, I am loading in a gltf file that is intended to be a contained space for a character to move around in. The file contains two models - 1 is the space, the other model (a plain cube) serves as a defined spawn point.

The model is exported from Blender as a glb file but was created with a uniform scale of 0.5.

If I was just normally loading this model into a suspended primitive, it all works as expected.

But my challenge here is the spawn object. I need to take its position (in order to set my spawn point) and then remove it from the scene. All good, except that if I have a collider specified as a Trimesh, the cube spawn point is wrapped as part of the Trimesh and even though the model is itself removed from the scene, the Trimesh and the physics of it being a fixed Rigidbody remain, because the collider is created automatically.

My strategy therefore, was to declare a RigidBody and ```colliders={false}``` so as I may defined that after the file loaded.

This is the declaration:

```
 <RigidBody position={modelPosition} type="fixed" scale={modelScale} ref={rigidBodyDeclared} colliders={false}>
      <Suspense fallback={<div>Loading Template Mesh...</div>}>
        <primitive ref={primativeRef} object={gltf.scene} />       
      </Suspense>
    </RigidBody>
```
You will note that I am also attempting to set the position and scale of the RigidBody.

![image](https://github.com/pmndrs/react-three-rapier/assets/107874035/3cd26425-41ad-4b0b-82d7-cf1accffefc9)

So what you see in this image, is the primitive loaded correctly and to the correct scale of 0.5 as well as the position of the model.

The debug of the collider shows it loaded at a uniform scale of 1 and a position of 0,0,0.

Here is the code I am using to create the Trimesh collider, after the model (shown here as baseLineElement) has loaded:

```

    var colliderDesc = physicsWorld?.rapier?.ColliderDesc.trimesh(
      baseLineElement.geometry.attributes.position.array as Float32Array,
      baseLineElement.geometry.index?.array as Uint32Array
    );

    const collider = physicsWorld.world.createCollider(colliderDesc, rigidBodyDeclared.current);    
```

My assumption would have been that a collider would normally have had its scale and position set by the parent RigidBody, as I find no methods to set them directly in code.

Is that intended to be the case, or is this not and I'm just out of luck?

I see in some of your source utils when automatically creating colliders that you are indeed taking the child scale into consideration.

Any thoughts, advice and or confirmation on this would be much appreciated.

**Comment by wiledal** [comment]
Since your are creating the colliders yourself, it's up to you to apply transform and position. You are creating the colliders based on vertices that you are providing yourself -- these will not be scaled unless you apply the scale to the geometry. Same goes with the position, you are creating this collider at the origin position and not changing it from what I can tell, which means it will end up at [0, 0, 0].

`r3/rapier` does all the scaling and transformation for you if you use the out-of-the box solution of a `<RigidBody colliders="trimesh" />`

What you want to be doing is import the `gltf` and wrapping the elements of the scene in the various colliders. You can use the primitives as you are doing here for that too.

```tsx
const Something = () => {
  const gltf = useGLTF('scene.glb')

  return <>
    <RigidBody position='fixed' colliders='trimesh'>
      <primitive object={gltf.nodes.map} />
    </RigidBody>
    <RigidBody position='fixed' colliders='trimesh'>
      <primitive object={gltf.nodes.somethingElse} />
    </RigidBody>
  </>
}
```

**Comment by OldManMeta** [comment]
Thanks for the response @wiledal - I see what you are saying. When you are using gltf.nodes etc, are you assuming that I have converted the model to a JSX component? Because that is not going to be the case here. It's a pure file load.

**Comment by OldManMeta** [comment]
Sorry, I just noticed that I can set the primitive object directly:

```
 <primitive ref={primativeRef} object={gltf.scene.getObjectByName('baseline')} />
```

Always learning new things. Thanks again.

**Comment by wiledal** [comment]
Ah! I recommend using helpers from `drei` for operations like that.
`useGLTF` gives you all the components of a gltf file broken into it's parts, like animations, nodes, materials. I use it every time I need to load something.

This is a pretty extensive example mixing a lot of techniques for building a game-experience.
https://codesandbox.io/s/trip-fellas-wip-9d4vm9
