### ISSUE TITLE
CuboidCollider nested rotation seems incorrect

### ISSUE THREAD

**Issue by ClayCooperLA** [pmndrs/react-three-rapier#42]
Unfortunately rapiers default collision detection is failing my models so I constructed some `CuboidColliders` in place and used `MeshCollider` to disable collision on the model. Seems like the relative translation of the parent rotation is off with the `CuboidColliders`. Or maybe I'm doing this wrong?

https://codesandbox.io/s/rapier-physics-box-fan-experiment-collision-rotation-iptdes?file=/src/BoxFan/FanCollider.js:927-972

🙇‍♂️

**Comment by wiledal** [comment]
That looks really strange indeed. Have you checked to see if visually the collisions actually make sense? The `<Debug />` component needs some work, and it might be interpreting the translations incorrectly.

**Comment by wiledal** [comment]
Uh, yeah those colliders are all over the place...
https://codesandbox.io/s/rapier-physics-box-fan-experiment-collision-rotation-forked-f1yh5w?file=/src/BoxFan/FanCollider.js

This does not seem to be the case in any of the `/demo` examples, I'm not sure what's going on.

**Comment by wiledal** [comment]
Ahh, the issues are coming from the rotation added to the Colliders, will investigate further.

**Comment by wiledal** [comment]
Thanks for all the debugging help 😅 @ClayCooperLA 
The rotations should now be predictable in 0.5.2!

https://codesandbox.io/s/rapier-physics-box-fan-experiment-collision-rotation-forked-l27no8?file=/src/BoxFan/FanCollider.js

**Comment by ClayCooperLA** [comment]
Thank you so much! @wiledal! Working perfectly now!
