### ISSUE TITLE
Some Demos are laggy in Edge browser. Is it only me?

### ISSUE THREAD

**Issue by RakaDoank** [pmndrs/react-three-rapier#448]
Some demos like these
[Performance](https://react-three-rapier.pmnd.rs/performance)
[Instanced Meshes](https://react-three-rapier.pmnd.rs/instanced-meshes)
[Instanced Meshes Compound](https://react-three-rapier.pmnd.rs/instanced-meshes-compound)

are slow in my Microsoft Edge when objects are colliding. I didn't test it yet on another device.
Those demos are bitterly smooth on Firefox and Chrome.

I asked this because i also got the same issue. I created an animation that principal is same as the performance demo. When there are objects dropping and colliding each other, make it dead/disappear when in certain positions, and make a new one. It is smooth in development with Next.js, but laggy on production like those demos only in the Edge browser.

Device specs and the software
- AMD Ryzen 5600H
- RTX 3060
- Windows 11 22H2
- Microsoft Edge (Version 114.0.1823.43 (Official build) (64-bit))

https://github.com/pmndrs/react-three-rapier/assets/23445738/a053eee0-9f99-478b-a587-b82915f95f47

**Comment by wiledal** [comment]
Interesting. 

> I created an animation that principal is same as the performance demo

Just to be clear, are you saying you are _also_ seeing performance issues on Edge unrelated to @react-three/rapier?

**Comment by RakaDoank** [comment]
When i wrote that, i was sure it was related to @react-three/rapier.

But now, probably, it is also unrelated to @react-three/rapier, because i also opened the [rapier.rs 3d demo](https://rapier.rs/demos3d/index.html) on Edge browser, get the same laggy on some demos.

**Comment by wiledal** [comment]
Oof, that sucks a bit! I haven't heard of this before. But at least it's out of the context of this library.
