### ISSUE TITLE
PrismaticJointParams don’t match up with usePrismaticJoint

### ISSUE THREAD

**Issue by KN3LL2K** [pmndrs/react-three-rapier#449]
I’ve noticed the usePrismaticJoints hook accepts 4 params (body1anchor, body2anchor, axis, limits) while the PrismaticJointParams have 6 params https://pmndrs.github.io/react-three-rapier/types/PrismaticJointParams.html

I noticed the y property of the 4th arg I pass in acts as a limit (confirmed by checked joint.limitMax()), and the x property will shift the joint on the x axis.

**Comment by KN3LL2K** [comment]
Workaround is to use joint.setLimits(min,max)

**Comment by wiledal** [comment]
Interesting! The docs correlate with what you are saying, https://www.rapier.rs/docs/user_guides/javascript/joints#prismatic-joint, but the implemented types do not 
<img width="604" alt="Screenshot 2023-06-19 at 18 57 55" src="https://github.com/pmndrs/react-three-rapier/assets/1035169/5fa7629e-aa45-4445-ba89-e54270b133af">

**Comment by wiledal** [comment]
The Rapier docs are incorrect, outdated, or reflect a future version 🤷 
I've updated the PrismaticJointParams to reflect the current version of the api.
