### ISSUE TITLE
Restore world from snapshot

### ISSUE THREAD

**Issue by verybomb** [pmndrs/react-three-rapier#514]
In rapier.js, you can take snapshots of the world and later restore it:
https://github.com/dimforge/rapier.js/blob/3b7484fb91ce00f44d9224943293e0b1728b8758/testbed3d/src/Testbed.ts#L136

How can I achieve this in react rapier?

**Comment by acorn1010** [comment]
+1. This feature is a requirement for a multiplayer game I'm working on. Without it, I have to use rapier directly instead of via `react-rapier`.

**Comment by kayden1940** [comment]
https://github.com/pmndrs/react-three-rapier/pull/563

I was looking for this feature as well and made one in my fork, demo is in the pull request.

**Comment by wiledal** [comment]
This should now be possible in 1.2.0! 
See https://github.com/pmndrs/react-three-rapier#snapshots

The implementation might be rudimentary, however. Let me know.
Thanks to @kayden1940 for the initial implementation of this.
