### ISSUE TITLE
[Question] Is there a way to put physic on pause?

### ISSUE THREAD

**Issue by fgarrec0397** [pmndrs/react-three-rapier#52]
I'm currently working on a game engine with React-Three-Fiber and I'm now looking for the best physic engine possible and this one looks great!

I would like to know if there is a way to put the physic on pause (just like use-cannon) which I was not able to find in the documentation.

Thanks!

**Comment by wiledal** [comment]
Good feature! Adding this to the current working branch.

**Comment by fgarrec0397** [comment]
Damn that was fast, thanks a lot!!
