### ISSUE TITLE
Can Groups within RigidBody receive scale, position, and rotation?

### ISSUE THREAD

**Issue by ClayCooperLA** [pmndrs/react-three-rapier#53]
Not sure if this is a bug. Scale seems to work on groups but position and rotation do not. Would be really awesome if groups could work the same as meshes. Position and rotation work as expected when put directly on the model mesh inside a RigidBody.

https://codesandbox.io/s/reverse-gravity-box-example-react-three-rapier-debug-group-p0sf4v?file=/src/BoxFan/TestCollider.js

:bow:

**Comment by wiledal** [comment]
This is supposed to work indeed! Will look over the world transforms!

**Comment by loukylor** [comment]
Do you have any possible workarounds?

**Comment by wiledal** [comment]
This will be fixe in #100
