### ISSUE TITLE
CollisionPayload - event and other types not directly available.

### ISSUE THREAD

**Issue by Seanmclem** [pmndrs/react-three-rapier#569]
Using:
```
"@react-three/fiber": "^8.15.11",
"@react-three/rapier": "^1.1.2",
```

This [sensor example, from docs](https://github.com/pmndrs/react-three-rapier#sensors), for context.

When using a `CuboidCollider` with a prop/function for `onIntersectionEnter`, the event passed into that function from that handler is of **_type_** `CollisionPayload`. That type is not directly exported or available from the library. I was able to import it like:
```
import type { CollisionPayload } from "@react-three/rapier/dist/declarations/src";
```
Which is really not ideal.  Is there supposed to be an easier way that I'm just not seeing? OR do some of these types need to be easier to import? If this is the only way- then that's the issue. Types not directly exported to the library.

**Comment by Seanmclem** [comment]
Actually, maybe none of my types are working properly? No auto-imports etc. I'm using Vite

### Package.json
```
{
  "name": "ecctrl-game-stuff-2",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite --host",
    "build": "tsc && vite build",
    "lint": "eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0",
    "preview": "vite preview"
  },
  "dependencies": {
    "@react-three/drei": "^9.88.17",
    "@react-three/fiber": "^8.15.11",
    "@react-three/rapier": "^1.1.2",
    "ecctrl": "^1.0.50",
    "leva": "^0.9.35",
    "r3f-perf": "^7.1.2",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "three": "^0.158.0",
    "zustand": "^4.4.6"
  },
  "devDependencies": {
    "@types/react": "^18.2.37",
    "@types/react-dom": "^18.2.15",
    "@types/three": "^0.158.3",
    "@typescript-eslint/eslint-plugin": "^6.10.0",
    "@typescript-eslint/parser": "^6.10.0",
    "@vitejs/plugin-react": "^4.2.0",
    "eslint": "^8.53.0",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-refresh": "^0.4.4",
    "typescript": "^5.2.2",
    "vite": "^5.0.0"
  }
}

```

**Comment by wiledal** [comment]
Hmm, unsure. I often have issues with types on CodeSandbox. However, the type is definitely exported. This is in a fresh Next.js project.

![Screenshot 2023-12-05 at 21 58 26](https://github.com/pmndrs/react-three-rapier/assets/1035169/2cc12a9c-fbfc-4d23-85cd-717f84bcfc71)

This is the default `tsconfig.json`.

```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
```

**Comment by Seanmclem** [comment]
@wiledal I'm just using vscode. what's your package.json look like?

**Comment by wiledal** [comment]
Here!
```json
{
  "name": "r3r-test",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@react-three/fiber": "^8.15.12",
    "@react-three/rapier": "^1.2.0",
    "next": "14.0.3",
    "react": "^18",
    "react-dom": "^18",
    "three": "^0.159.0"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "autoprefixer": "^10.0.1",
    "eslint": "^8",
    "eslint-config-next": "14.0.3",
    "postcss": "^8",
    "tailwindcss": "^3.3.0",
    "typescript": "^5"
  }
}
```

But that shouldn't really matter -- usually if this happens it means your tsconfig is strange, or you just need to restart your TypeScript server.

![Screenshot 2023-12-05 at 22 16 48](https://github.com/pmndrs/react-three-rapier/assets/1035169/c15aa894-1371-45ad-a6d0-0cdfb4ffbb2a)

That should re-index the project.

**Comment by Seanmclem** [comment]
after more closely following a dependency list like yours, and deleting and reinstalling node_modules, it all works fine now. thanks
