### ISSUE TITLE
Dynamic creation of RigidBody for specific models within a glTF file.

### ISSUE THREAD

**Issue by JacobOsense2223** [pmndrs/react-three-rapier#617]
How can I dynamically generate RigidBody for specific sub-objects of a glTF model?

**Comment by wiledal** [comment]
When importing the gltf, you get an outline of the entire scene.
You can use that outline to map out each child and wrap them within a RigidBody.

```ts
const Component = () => {
  const gltf = useGLTF('/something.gltf')
  
  return <>
    {Object.values(gltf.nodes).map(node => <RigidBody>{node}</RigidBody>)}
  </>
}
```

Example:
https://codesandbox.io/p/sandbox/angery-berbs--asset-transforms-from-blender-ebl16y?file=%2Fsrc%2FApp.tsx%3A8%2C7
