### ISSUE TITLE
When kinematicPosition hits a fixed object. No event is emitted.

### ISSUE THREAD

**Issue by intentmoose** [pmndrs/react-three-rapier#644]
Im moving a RigidBody with `type="kinematicPosition"`. And want to emit an event when it hits a `type="fixed"`.
For some reason the event does not emit. Unless the fixed is hit with a `type="dynamic"`.

**Comment by isaac-mason** [comment]
Hi, I'll close this issue seeing as you opened a feature request issue that will address this: https://github.com/pmndrs/react-three-rapier/issues/674
