### ISSUE TITLE
Update @dimforge/rapier3d-compat to 0.13.0

### ISSUE THREAD

**Issue by isaac-mason** [pmndrs/react-three-rapier#667]
@dimforge/rapier3d-compat has been released - creating this issue to track updating rt/rapier and exposing new functionality.

https://github.com/dimforge/rapier.js/pull/273

Looking at the release notes, these look like the main things we'll want to expose in the existing react APIs:

- [x] Collider contact skin - https://github.com/dimforge/rapier/pull/625
- [x] Rigid body soft ccd - https://github.com/dimforge/rapier/pull/625
- [x] World.lengthUnit - "which can be used to indicate the typical size of dynamic objects (e.g. 100 pixels instead of
1 meter)"

**Comment by intentmoose** [comment]
What about [ActiveCollisionTypes](https://rapier.rs/docs/user_guides/rust/colliders#active-collision-types) so we can [enable contacts between static/kinematic bodies](https://docs.rs/rapier3d/latest/rapier3d/geometry/struct.ActiveCollisionTypes.html#associatedconstant.KINEMATIC_FIXED).

**Comment by isaac-mason** [comment]
From a breif look doesn't look like that was added in 0.13.0, but for sure we should make sure it's exposed.

**Comment by isaac-mason** [comment]
Ah thanks for opening an issue 👍 (https://github.com/pmndrs/react-three-rapier/issues/674)
