### ISSUE TITLE
ActiveCollisionTypes to enable contacts between static and kinematic bodies.

### ISSUE THREAD

**Issue by intentmoose** [pmndrs/react-three-rapier#674]
Are there plans to implement [ActiveCollisionTypes](https://rapier.rs/docs/user_guides/rust/colliders#active-collision-types)? so we can [enable contacts between static and kinematic bodies](https://docs.rs/rapier3d/latest/rapier3d/geometry/struct.ActiveCollisionTypes.html#associatedconstant.KINEMATIC_FIXED).

Seems to be some of Rapiers new features

**Comment by isaac-mason** [comment]
A <RigidBody \/> prop activeCollisionTypes has been added in 0.14.0.

https://react-three-rapier.pmnd.rs/active-collision-types
See: https://github.com/pmndrs/react-three-rapier/blob/582faa1f5b52d72cdaa31ade1eb338f08e9d08d2/demo/src/examples/active-collision-types/ActiveCollisionTypesExample.tsx#L50
