### ISSUE TITLE
RigidBody not updating on drag

### ISSUE THREAD

**Issue by AshhadDevLab** [pmndrs/react-three-rapier#688]
## Description:

I am using DragControls over a RigidBody. The issue I am facing performing this action is that the mesh is moving with the drag controls, whereas the rigid body or the physics component stays where it is and doesn't move.

## Code

 [CodeSandbox](https://codesandbox.io/p/sandbox/rigidbody-issue-6rx3pn)
 
 ## Tried Solutions:
 
 I tried copying the world position of the original geometry and then update the position of the rigid body with respect to the world position.

**Comment by niccolofanton** [comment]
I was facing a similar problem, I think it's not possible to use a DragControl with a RigidBody directly inside. 

When you drag, the control moves the mesh, and if you translate the RigidBody programmatically to the new position it will move again the mesh causing a chain reaction.

I solved using a RigidBody with a mesh inside and a DragControl with the same mesh but invisible.

**Comment by about-daniel** [comment]
> I was facing a similar problem, I think it's not possible to use a DragControl with a RigidBody directly inside.
> 
> When you drag, the control moves the mesh, and if you translate the RigidBody programmatically to the new position it will move again the mesh causing a chain reaction.
> 
> I solved using a RigidBody with a mesh inside and a DragControl with the same mesh but invisible.

Hey, have you an example of your solution?

`<RigidBody
        linearDamping={0.75}
        angularDamping={0.15}
        friction={0.2}
        position={[
          (Math.random() * viewport.width) / 2 - viewport.width / 2,
          (Math.random() * viewport.height) / 2 + viewport.height / 2,
          Math.random() * 15 - 8,
        ]}
        colliders={false}
        dispose={null}
      >
          <BallCollider args={[scale]} />
          <CylinderCollider
            rotation={[Math.PI / 2, 0, 0]}
            position={[0, 0, 1.2 * scale]}
            args={[0.15 * scale, 0.275 * scale]}
          />
          <mesh
            castShadow
            receiveShadow
            scale={scale}
            geometry={sphereGeometry}
            material={baubleMaterial}
          />
          <mesh
            castShadow
            scale={2.5 * scale}
            position={[0, 0, -1.8 * scale]}
            geometry={nodes.Mesh_1.geometry}
            material={capMaterial}
          />
      </RigidBody>`
      
   I need to make this draggable
