### ISSUE TITLE
Can't configure collision masks and groups for colliders, and active collision types

### ISSUE THREAD

**Issue by hmans** [pmndrs/react-three-rapier#79]
#### As Is:

There doesn't seem to be a way to configure collision masks and groups for colliders, or their active collision types.

#### To Be:

There needs to be a way to configure collision masks and groups for colliders, and active collision types. These are just bitmasks (expressed as numbers), so ideally there should be a supplementary API for creating them without requiring the user to do the math. (In an earlier project, I had a `collisions(group, mask)` helper that would return the correct numerical value.

Further reading:

- https://rapier.rs/docs/user_guides/javascript/colliders#collision-groups-and-solver-groups
- https://rapier.rs/docs/user_guides/javascript/colliders#active-collision-types

#### Why is this important:

Games need to control exactly which bodies (colliders) are supposed to collide with what other bodies (colliders), and which of them generate collision events.

**Comment by t-gilb** [comment]
Hi @wiledal @hmans.

I'm trying to allow collision between  two colliders not attached to dynamic bodies (I want to allow collision between a collider attached to a kinematic rigid-body and a collider attached to a fixed rigid-body). 

For now, I did not find the proper way to do it using react-three-rapier (documentation and examples).
Could you tell me how I could do or where I could find some documentation ? 

Thanks,
Thomas.
