### ISSUE TITLE
Will there be support on Next.js in the future?

### ISSUE THREAD

**Issue by kayden1940** [pmndrs/react-three-rapier#88]
Tried to import anything from rapier, ocurrs error:

Error: Cannot find module '/repo/node_modules/three/examples/jsm/utils/BufferGeometryUtils'
  
I thinks rapier was trying to get example stuff from three which npm three don't have, hence the error.

Can I tricks rapier to get examples from three-stdlib?

I was running in the latest Next.js, r3f and three.

**Comment by AaronClaes** [comment]
same problem here

**Comment by Skarian** [comment]
Same issue as well

**Comment by merveillevaneck** [comment]
would be cool to see this gain support on NextJS as well. not sure if it works on remix but i will run a test on my end to see if it can work.

**Comment by firtoz** [comment]
A workaround is to put your scene contents into a dynamic import e.g.

```tsx

const Content = dynamic(async () => {
  const content = await import('./path-to-content');

  return content.Content;
}, {
  ssr: false,
});
```

Then it will work only on client side which seems to work well for me.

**Comment by merveillevaneck** [comment]
nice! That's a pretty smart workaround. Another option is to
use @react-three/cannon which i believe is the same underlying packages
under the hood, but cannon renders purely client side as far as i know!
cannon is working pretty well on nextjs check out
https://kilo-geo.netlify.app do see a working physics scene. code is at
https://www.github.com/merveillevaneck/geo

**Comment by merveillevaneck** [comment]
Alright, interesting. Do you know maybe why there are multiple?

**Comment by hmans** [comment]
> Alright, interesting. Do you know maybe why there are multiple?

I'm not sure I understand the question. Are you asking why multiple physics engines exist?

**Comment by merveillevaneck** [comment]
Almost. I’m essentially asking what the different intentions are between
the two and also why two different dependencies were created and managed in
the context of @react-three.

**Comment by isaac-mason** [comment]
@react-three/cannon was created first. The cannon physics engine is written in JavaScript, and while it's impressive and works for many projects, it has limitations.

@react-three/rapier was more recently created and uses the rust rapier physics engine. Rapier is more feature complete and performance, but it has a larger wasm bundle. 

As rt/rapier matures, it will be the obvious choice for most projects. 

There will still be a place for rt/cannon in some projects that only need simple physics and small bundle sizes, but it's possible the bundle size for rapier can be reduced in future.
